# Generated by Django 4.1 on 2023-04-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_assignment_file_alter_submission_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='instructor',
        ),
    ]
