# Generated by Django 4.1 on 2023-04-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_assignment_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='github_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
